- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Installing Htop,ncdu,apache2..
      apt:
        name: "{{item}}"
        state: absent
      with_items:
        - htop
        - ncdu
        - apache2

    - name: Configuring webserver
      raw: echo "hello world" > /var/www/html/index.html

    - name: Configuring the apache2 server from port 80 to 8085.
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: Listen 8085

    - name: Restarting the webserver...
      service:
        name: apache2
        state: restarted
    - name: Creating cron in User's machine.
      lineinfile:
        path: /etc/crontab
        line: '* * * * *       root    ansible-pull -U https://github.com/Naga-ganesh/htop.git -o'

