- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Installing Htop,ncdu,apache2..
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - htop
        - ncdu
        - apache2

    - name: Configuring webserver
      lineinfile:
        path: /var/www/html/index.html
        line: Hello world

    - name: Configuring the apache2 server from port 80 to 8081.
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: Listen 8085
        
    - name: Restarting the webserver...
      service:
        name: apache2
        state: restarted
