- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Installing Htop,ncdu,apache2..
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - htop
        - ncdu
        - apache2
    - name: Configuring webserver
      raw: echo "hello world" > /var/www/html/index.html
    - name: Configuring the apache2 port to 8081
      lineinfile:
        line: Listen 8085
        path: /etc/apache2/ports.conf
        regexp: '^Listen 8081'
        
