- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name:
      apt:
        name: '{item}'
        state: present
        update_cache: yes
      with_items:
        - htop
        - ncdu
        
